services:
  - type: web
    name: kothakunjo-search-engine-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT --log-level info --timeout-keep-alive 30"
    envVars:
      - key: MISTRAL_API_KEY
        fromDatabase:
          name: kothakunjo-search-engine-backend
          property: mistral-api-key
      - key: OPENROUTER_API_KEY
        fromDatabase:
          name: kothakunjo-search-engine-backend
          property: openrouter-api-key
      - key: SERPAPI_API_KEY
        fromDatabase:
          name: kothakunjo-search-engine-backend
          property: serpapi-api-key
    regions:
      - singapore
    plan: free
    buildFilter:
      paths:
        - app.py
        - inference.py
        - utils.py
        - requirements.txt